name: Docker GHCR
permissions: write-all

on:
  workflow_dispatch:
    inputs:
      service:
        type: string
  workflow_call:
    inputs:
      service:
        required: true
        type: string

jobs:
  docker:
    name: Docker GHCR
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Downcase repository name
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          echo "GITHUB_REPOSITORY=$(echo "$GITHUB_REPOSITORY" | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v5
        env:
          NAME: ${{ env.GITHUB_REPOSITORY }}-${{ inputs.service }}
          AT_ROOT: "{{defaultContext}}"
          WITH_SUBFOLDER: "{{defaultContext}}:${{ inputs.service }}"
        with:
          context: ${{inputs.service == '' && env.AT_ROOT || env.WITH_SUBFOLDER }}
          push: true
          tags: ghcr.io/${{ env.NAME }}:latest
          cache-from: type=gha,scope=${{ env.NAME }}
          cache-to: type=gha,mode=max,scope=${{ env.NAME }}
